name: AI Updater Workflow (dev branch for testing in fork)

on:
  push:
    branches:
      - workflow/update-proto
  workflow_dispatch:

jobs:
  call-ai-updater:
    uses: gabegottlob/viam-ai-updater/.github/workflows/ai-updater-dev.yml@develop
    with:
        target_branch: workflow/update-proto
        sdk: python
    secrets:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
