name: Test Experimental AI Updater Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - workflow/update-proto

jobs:
  call-ai-updater:
    uses: gabegottlob/viam-ai-updater/.github/workflows/ai-updater-exp.yml@experiment
    with:
        target_branch: workflow/update-proto
    secrets:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
